-- MySQL Script generated by MySQL Workbench
-- Sex 19 Jan 2018 15:47:07 -02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema banco_teste
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banco_teste
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banco_teste` DEFAULT CHARACTER SET utf8 ;
USE `banco_teste` ;

-- -----------------------------------------------------
-- Table `banco_teste`.`contas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_teste`.`contas` (
  `id` INT NOT NULL,
  `usuario` INT NULL,
  `valor` DECIMAL(10,2) NULL,
  `qtd_parcelas` INT NULL,
  `fornecedor` VARCHAR(150) NULL,
  `conta` VARCHAR(150) NULL,
  `id_cliente` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_general_ci;


-- -----------------------------------------------------
-- Table `banco_teste`.`contas_pagar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_teste`.`contas_pagar` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `numeroparcela` INT(11) NULL,
  `valorparcela` DECIMAL(10,2) NULL,
  `status` VARCHAR(45) NULL,
  `valorpago` DECIMAL(10,2) NULL,
  `idcontas` INT NULL,
  `vencimento` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contas_pagar_1_idx` (`idcontas` ASC),
  CONSTRAINT `fk_contas_pagar_1`
    FOREIGN KEY (`idcontas`)
    REFERENCES `banco_teste`.`contas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_general_ci;


-- -----------------------------------------------------
-- Table `banco_teste`.`contas_receber`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_teste`.`contas_receber` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `numeroparcela` INT(11) NULL,
  `valorparcela` DECIMAL(10,2) NULL,
  `status` VARCHAR(45) NULL,
  `valorpago` DECIMAL(10,2) NULL,
  `idcontas` INT NULL,
  `vencimento` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contas_receber_1_idx` (`idcontas` ASC),
  CONSTRAINT `fk_contas_receber_1`
    FOREIGN KEY (`idcontas`)
    REFERENCES `banco_teste`.`contas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_general_ci
COMMENT = 'Tabela de cadastro de contas a receber de vendas de produtos.';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
